# Site settings
title: price comstock
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  the official blog of price comstock
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: price_comstock
github_username:  pricecomstock

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]

highlighter: rouge

# DOCS https://jekyllrb.com/docs/pagination/
# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


